packages:
  - apps/*
  - packages/*
  - jobs/*
  - cron/*

catalog:
  '@types/amqplib': 0.10.7
  '@types/bun': 1.2.23
  '@types/node': 24.5.2
  '@types/react': 19.2.0
  '@types/react-dom': 19.2.0
  amqp-connection-manager: 5.0.0
  amqplib: 0.10.9
  elysia: 1.4.9
  next: 15.5.4
  react: 19.2.0
  react-dom: 19.2.0
  zod: 4.1.11

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - core-js
  - core-js-pure
  - esbuild
  - protobufjs
  - puppeteer
  - sharp
