services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      # Admin credentials
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

      # Database configuration
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresql:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_password

      # Enable health and metrics
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    ports:
      - '8080:8080' # HTTP port
      - '9000:9000' # Health/metrics port
    volumes:
      - keycloak_data:/opt/keycloak/data
    command: ['start-dev']
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/health/ready']
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  keycloak_data:
