services:
  openfga-migrate:
    image: openfga/openfga:latest
    container_name: openfga-migrate
    command: migrate
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://openfga:openfga_password@postgresql:5432/openfga?sslmode=disable
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - default

  openfga:
    image: openfga/openfga:latest
    container_name: openfga
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://openfga:openfga_password@postgresql:5432/openfga?sslmode=disable
      - OPENFGA_LOG_FORMAT=json
      - OPENFGA_LOG_LEVEL=info
      - OPENFGA_METRICS_ENABLED=true
      - OPENFGA_METRICS_ADDR=0.0.0.0:2112
      - OPENFGA_TRACE_ENABLED=true
      - OPENFGA_TRACE_OTLP_ENDPOINT=0.0.0.0:4317
      - OPENFGA_TRACE_SAMPLE_RATIO=1.0
      - OPENFGA_PLAYGROUND_ENABLED=true
      - OPENFGA_PLAYGROUND_PORT=3000
    command: run
    depends_on:
      openfga-migrate:
        condition: service_completed_successfully
    ports:
      - "8082:8080"  # HTTP API
      - "8081:8081"  # gRPC API
      - "3901:3000"  # Playground
      - "2112:2112"  # Metrics
      - "4317:4317"  # Tracing
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - default
